# I like to use this file with more Madicken-specific variables. For machine
# made and other global variables, look at .profile or .bash_profile





# PATHS


# PATHS for Exhnihilo development environment
PATH="/Users/madicken/Install/Exnihilo-for-advantg-debug/bin:/Users/madicken/Install/advantg-debug/bin:/data/env/bin:${PATH}"
export PATH

# TEXINPUTS="/data/env/latex"
# export TEXINPUTS

BSTINPUTS="/data/env/bibtex"
export BSTINPUTS

PYTHONPATH="/Users/madicken/Install/Exnihilo-for-advantg-debug/python:${PYTHONPATH}"
export PYTHONPATH

PYTHONPATH="/Users/madicken/Install/advantg-debug/lib/python2.7/site-packages:${PYTHONPATH}"

export DATAPATH="/Users/madicken/Install/mcnp/data"

# Alias definitions
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly. See
# /usr/share/doc/bash-doc/examples in the bas-doc package. 

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi


export CLICOLOR=1
export LSCOLOR

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt 
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
  # We have color support; assume it's compliant with Ecma-48
  # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
  # a case would tend to support setf rather than setaf.)
  color_prompt=yes
    else
  color_prompt=
    fi
fi

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

if [ "$color_prompt" = yes ]; then
    PS1="${debian_chroot:+($debian_chroot)}\[\033[01;33m\]madmunk@\h\[\033[00m\]:\[\033[01;32m\]\w\[\033[00m\]\$(parse_git_branch) $ "
else
    PS1="${debian_chroot:+($debian_chroot)}madmunk@\h:\w\$(parse_git_branch) $"
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac


# Set colors to match iterm2 Terminal Colors
export TERM=xterm-256color
